export const ThemeColor = {
    PRM: "primary",
    PRM_L:"primary-light",
    PRM_D: "primary-ark",
    SCD: "secondary",
    SCD_L:"secondary-light",
    SCD_D:"secondary-dark",
    NEG: 'negative',
    NEG_L:"negative-light",
    NEG_D:"negative-dark",
    POS: 'positive',
    POS_L:"positive-light",
    POS_D:"positive-dark",
    PRM_BG:'primary-background',
    PRM_BG_L:'primary-background-light',
    PRM_BG_D:'primary-background-dark',
    SCD_BG:'secondary-background',
    SCD_BG_L:'secondary-background-light',
    SCD_BG_D:'secondary-background-dark',
    PRM_TXT:'primary-text',
    PRM_TXT_L:'primary-text-light',
    PRM_TXT_D:'primary-text-dark',
    SCD_TXT:'secondary-text',
    SCD_TXT_L:'secondary-text-light',
    SCD_TXT_D:'secondary-text-dark',
}